# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
  git clone https://github.com/sn-rad-trans/code-comparison1.git
  mkdir data1
  mv toy01 toy06 ddc10 ddc25 data1
  mv data1 code-comparison1
  ls *
  displayName: 'Prepare the data'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
